/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanesIndexRouteImport } from './routes/lanes.index'
import { Route as PathsLibraryRouteImport } from './routes/paths.library'
import { Route as LanesNewRouteImport } from './routes/lanes.new'
import { Route as LanesIdRouteImport } from './routes/lanes.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InviteTokenWelcomeRouteImport } from './routes/invite.$token.welcome'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPublicHooksMissedCheckinsRouteImport } from './routes/api/public/hooks/missed-checkins'
import { Route as ApiPublicHooksEscalateMissedRouteImport } from './routes/api/public/hooks/escalate-missed'
import { Route as ApiPublicHooksBedtimeReminderRouteImport } from './routes/api/public/hooks/bedtime-reminder'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesIndexRoute = LanesIndexRouteImport.update({
  id: '/lanes/',
  path: '/lanes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsLibraryRoute = PathsLibraryRouteImport.update({
  id: '/paths/library',
  path: '/paths/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesNewRoute = LanesNewRouteImport.update({
  id: '/lanes/new',
  path: '/lanes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesIdRoute = LanesIdRouteImport.update({
  id: '/lanes/$id',
  path: '/lanes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenWelcomeRoute = InviteTokenWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => InviteTokenRoute,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMissedCheckinsRoute =
  ApiPublicHooksMissedCheckinsRouteImport.update({
    id: '/api/public/hooks/missed-checkins',
    path: '/api/public/hooks/missed-checkins',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEscalateMissedRoute =
  ApiPublicHooksEscalateMissedRouteImport.update({
    id: '/api/public/hooks/escalate-missed',
    path: '/api/public/hooks/escalate-missed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBedtimeReminderRoute =
  ApiPublicHooksBedtimeReminderRouteImport.update({
    id: '/api/public/hooks/bedtime-reminder',
    path: '/api/public/hooks/bedtime-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRouteWithChildren
  '/lanes/$id': typeof LanesIdRoute
  '/lanes/new': typeof LanesNewRoute
  '/paths/library': typeof PathsLibraryRoute
  '/lanes/': typeof LanesIndexRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/invite/$token/welcome': typeof InviteTokenWelcomeRoute
  '/api/public/hooks/bedtime-reminder': typeof ApiPublicHooksBedtimeReminderRoute
  '/api/public/hooks/escalate-missed': typeof ApiPublicHooksEscalateMissedRoute
  '/api/public/hooks/missed-checkins': typeof ApiPublicHooksMissedCheckinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRouteWithChildren
  '/lanes/$id': typeof LanesIdRoute
  '/lanes/new': typeof LanesNewRoute
  '/paths/library': typeof PathsLibraryRoute
  '/lanes': typeof LanesIndexRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/invite/$token/welcome': typeof InviteTokenWelcomeRoute
  '/api/public/hooks/bedtime-reminder': typeof ApiPublicHooksBedtimeReminderRoute
  '/api/public/hooks/escalate-missed': typeof ApiPublicHooksEscalateMissedRoute
  '/api/public/hooks/missed-checkins': typeof ApiPublicHooksMissedCheckinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRouteWithChildren
  '/lanes/$id': typeof LanesIdRoute
  '/lanes/new': typeof LanesNewRoute
  '/paths/library': typeof PathsLibraryRoute
  '/lanes/': typeof LanesIndexRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/invite/$token/welcome': typeof InviteTokenWelcomeRoute
  '/api/public/hooks/bedtime-reminder': typeof ApiPublicHooksBedtimeReminderRoute
  '/api/public/hooks/escalate-missed': typeof ApiPublicHooksEscalateMissedRoute
  '/api/public/hooks/missed-checkins': typeof ApiPublicHooksMissedCheckinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkin'
    | '/dashboard'
    | '/demo'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/partner'
    | '/settings'
    | '/terms'
    | '/invite/$token'
    | '/lanes/$id'
    | '/lanes/new'
    | '/paths/library'
    | '/lanes/'
    | '/api/push/subscribe'
    | '/invite/$token/welcome'
    | '/api/public/hooks/bedtime-reminder'
    | '/api/public/hooks/escalate-missed'
    | '/api/public/hooks/missed-checkins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkin'
    | '/dashboard'
    | '/demo'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/partner'
    | '/settings'
    | '/terms'
    | '/invite/$token'
    | '/lanes/$id'
    | '/lanes/new'
    | '/paths/library'
    | '/lanes'
    | '/api/push/subscribe'
    | '/invite/$token/welcome'
    | '/api/public/hooks/bedtime-reminder'
    | '/api/public/hooks/escalate-missed'
    | '/api/public/hooks/missed-checkins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkin'
    | '/dashboard'
    | '/demo'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/partner'
    | '/settings'
    | '/terms'
    | '/invite/$token'
    | '/lanes/$id'
    | '/lanes/new'
    | '/paths/library'
    | '/lanes/'
    | '/api/push/subscribe'
    | '/invite/$token/welcome'
    | '/api/public/hooks/bedtime-reminder'
    | '/api/public/hooks/escalate-missed'
    | '/api/public/hooks/missed-checkins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRouteWithChildren
  LanesIdRoute: typeof LanesIdRoute
  LanesNewRoute: typeof LanesNewRoute
  PathsLibraryRoute: typeof PathsLibraryRoute
  LanesIndexRoute: typeof LanesIndexRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPublicHooksBedtimeReminderRoute: typeof ApiPublicHooksBedtimeReminderRoute
  ApiPublicHooksEscalateMissedRoute: typeof ApiPublicHooksEscalateMissedRoute
  ApiPublicHooksMissedCheckinsRoute: typeof ApiPublicHooksMissedCheckinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/': {
      id: '/lanes/'
      path: '/lanes'
      fullPath: '/lanes/'
      preLoaderRoute: typeof LanesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/library': {
      id: '/paths/library'
      path: '/paths/library'
      fullPath: '/paths/library'
      preLoaderRoute: typeof PathsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/new': {
      id: '/lanes/new'
      path: '/lanes/new'
      fullPath: '/lanes/new'
      preLoaderRoute: typeof LanesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/$id': {
      id: '/lanes/$id'
      path: '/lanes/$id'
      fullPath: '/lanes/$id'
      preLoaderRoute: typeof LanesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token/welcome': {
      id: '/invite/$token/welcome'
      path: '/welcome'
      fullPath: '/invite/$token/welcome'
      preLoaderRoute: typeof InviteTokenWelcomeRouteImport
      parentRoute: typeof InviteTokenRoute
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/missed-checkins': {
      id: '/api/public/hooks/missed-checkins'
      path: '/api/public/hooks/missed-checkins'
      fullPath: '/api/public/hooks/missed-checkins'
      preLoaderRoute: typeof ApiPublicHooksMissedCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/escalate-missed': {
      id: '/api/public/hooks/escalate-missed'
      path: '/api/public/hooks/escalate-missed'
      fullPath: '/api/public/hooks/escalate-missed'
      preLoaderRoute: typeof ApiPublicHooksEscalateMissedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bedtime-reminder': {
      id: '/api/public/hooks/bedtime-reminder'
      path: '/api/public/hooks/bedtime-reminder'
      fullPath: '/api/public/hooks/bedtime-reminder'
      preLoaderRoute: typeof ApiPublicHooksBedtimeReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InviteTokenRouteChildren {
  InviteTokenWelcomeRoute: typeof InviteTokenWelcomeRoute
}

const InviteTokenRouteChildren: InviteTokenRouteChildren = {
  InviteTokenWelcomeRoute: InviteTokenWelcomeRoute,
}

const InviteTokenRouteWithChildren = InviteTokenRoute._addFileChildren(
  InviteTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRouteWithChildren,
  LanesIdRoute: LanesIdRoute,
  LanesNewRoute: LanesNewRoute,
  PathsLibraryRoute: PathsLibraryRoute,
  LanesIndexRoute: LanesIndexRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPublicHooksBedtimeReminderRoute: ApiPublicHooksBedtimeReminderRoute,
  ApiPublicHooksEscalateMissedRoute: ApiPublicHooksEscalateMissedRoute,
  ApiPublicHooksMissedCheckinsRoute: ApiPublicHooksMissedCheckinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
